# Generated by Django 2.2.5 on 2019-09-17 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('massemailer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='receiver',
            field=models.TextField(max_length=200),
        ),
    ]
