# Generated by Django 2.2.5 on 2019-09-18 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('massemailer', '0002_auto_20190917_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='body',
            field=models.TextField(default='Hello'),
        ),
        migrations.AddField(
            model_name='mail',
            name='subject',
            field=models.CharField(default='hello', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mail',
            name='receiver',
            field=models.TextField(),
        ),
    ]
