# Generated by Django 2.2.5 on 2019-09-18 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('massemailer', '0004_auto_20190918_2252'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scrapper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csvdump', models.TextField(default='dump csv here')),
            ],
        ),
    ]
