# Generated by Django 2.2.5 on 2019-09-19 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('massemailer', '0005_scrapper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapper',
            name='csvdump',
            field=models.TextField(default='insert website'),
        ),
    ]
