# Generated by Django 2.2.5 on 2019-09-22 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('massemailer', '0006_auto_20190919_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='attachments/'),
        ),
    ]
