# Generated by Django 2.2.5 on 2019-09-22 17:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('massemailer', '0008_mail_replymail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapper',
            name='csvdump',
            field=models.TextField(default='insert website', validators=[django.core.validators.RegexValidator(code='invalid_url', message='URL must be a proper url', regex="/^(?:http(s)?:\\/\\/)?[\\w.-]+(?:\\.[\\w\\.-]+)+[\\w\\-\\._~:/?#[\\]@!\\$&'\\(\\)\\*\\+,;=.]+$/gm")]),
        ),
    ]
