# Generated by Django 2.2.5 on 2019-09-22 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('massemailer', '0010_auto_20190922_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
